name: Tag

on:
  pull_request:
    types: [closed]
    branches:
      - master
    paths-ignore:
      - '.github/**'
      - 'trove-ci.yml'
      - '**/*.md'

permissions:
  contents: write

jobs:
  tag-release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Tag
        uses: anothrNick/github-tag-action@1.67.0
        id: tag
        env:
          WITH_V: true
          INITIAL_VERSION: 1.0.0
          DEFAULT_BUMP: ${{ (contains(github.event.pull_request.labels.*.name, 'bump major') && 'major') ||
                            (contains(github.event.pull_request.labels.*.name, 'bump patch') && 'patch') ||
                            'minor' }}

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag.outputs.new_tag }}
          name: ${{ github.event.pull_request.title }}
          body: |
            ### Release: ${{ steps.tag.outputs.new_tag }}
            Triggered by Pull Request: [${{ github.event.pull_request.title }}](${{ github.event.pull_request.html_url }})
